// Mocks generated by Mockito 5.2.0 from annotations
// in timezone_map/test/controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:timezone_map/src/location.dart' as _i5;
import 'package:timezone_map/src/service.dart' as _i2;
import 'package:timezone_map/src/source.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GeoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoService extends _i1.Mock implements _i2.GeoService {
  MockGeoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addSource(_i3.GeoSource? source) =>
      super.noSuchMethod(Invocation.method(#addSource, [source]),
          returnValueForMissingStub: null);
  @override
  void removeSource(_i3.GeoSource? source) =>
      super.noSuchMethod(Invocation.method(#removeSource, [source]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<_i5.GeoLocation?> lookupLocation() =>
      (super.noSuchMethod(Invocation.method(#lookupLocation, []),
              returnValue: Future<_i5.GeoLocation?>.value())
          as _i4.Future<_i5.GeoLocation?>);
  @override
  _i4.Future<Iterable<_i5.GeoLocation>> searchLocation(String? location) =>
      (super.noSuchMethod(Invocation.method(#searchLocation, [location]),
              returnValue:
                  Future<Iterable<_i5.GeoLocation>>.value(<_i5.GeoLocation>[]))
          as _i4.Future<Iterable<_i5.GeoLocation>>);
  @override
  _i4.Future<Iterable<_i5.GeoLocation>> searchCoordinates(
          _i5.LatLng? coordinates) =>
      (super.noSuchMethod(Invocation.method(#searchCoordinates, [coordinates]),
              returnValue:
                  Future<Iterable<_i5.GeoLocation>>.value(<_i5.GeoLocation>[]))
          as _i4.Future<Iterable<_i5.GeoLocation>>);
  @override
  _i4.Future<Iterable<_i5.GeoLocation>> searchTimezone(String? timezone) =>
      (super.noSuchMethod(Invocation.method(#searchTimezone, [timezone]),
              returnValue:
                  Future<Iterable<_i5.GeoLocation>>.value(<_i5.GeoLocation>[]))
          as _i4.Future<Iterable<_i5.GeoLocation>>);
  @override
  _i4.Future<void> cancelSearch() =>
      (super.noSuchMethod(Invocation.method(#cancelSearch, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}
