name: ubuntu_lints
description: Ubuntu lints package for Dart and Flutter.
version: 0.4.1
repository: https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_lints
issue_tracker: https://github.com/canonical/ubuntu-flutter-plugins/issues
topics:
  - lints

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_lints: ^5.0.0
  yaml: ^3.1.2

