name: handy_window_example
description: Demonstrates the handy_window plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  handy_window:
    path: ../
  url_launcher: ^6.1.0
  yaru: ^0.2.2

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
