name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos 2.9.0
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: melos bootstrap
    - run: melos build

  snap:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
    - run: dart pub global activate melos 2.9.0
    - run: sudo snap install --classic flutter
    - run: flutter doctor -v
    - run: melos bootstrap
    - run: melos build
