name: Generate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-runner:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos
    - run: melos bootstrap
    - run: melos run generate
    - run: ./.github/scripts/check-outdated-files.sh
      if: github.event_name == 'pull_request'
    - uses: peter-evans/create-pull-request@v5
      if: github.event_name == 'push'
      id: create-pr
      with:
        title: 'chore: regenerate l10n'
        commit-message: 'chore: regenerate l10n'
    - name: Auto-merge PR
      if: ${{steps.create-pr.outputs.pull-request-number}}
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{steps.create-pr.outputs.pull-request-url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  gen-l10n:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos
    - run: melos bootstrap
    - run: melos run gen-l10n
    - run: ./.github/scripts/check-outdated-files.sh
      if: github.event_name == 'pull_request'
    - uses: peter-evans/create-pull-request@v5
      if: github.event_name == 'push'
      id: create-pr
      with:
        title: 'chore: regenerate l10n'
        commit-message: 'chore: regenerate l10n'
    - name: Auto-merge PR
      if: ${{steps.create-pr.outputs.pull-request-number}}
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{steps.create-pr.outputs.pull-request-url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
