name: Tag and start release
on:
  push:
    branches: [main]

jobs:
  publish-packages:
    name: Create tags and start release
    permissions:
      contents: write
    runs-on: [ ubuntu-latest ]
    if: contains(github.event.head_commit.message, 'chore(release)')
    steps:
      - uses: actions/checkout@v4
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v3
        with:
          tag: true
      - run: |
          melos exec -c1 --no-published --no-private --order-dependents -- \
          gh workflow run release-publish.yml \
          --ref \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
