name: Release Please

on:
  workflow_call:

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: dart
          changelog-notes-type: github
          pull-request-title-pattern: 'chore: release v${version}'
