name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos 2.9.0
    - run: sudo apt update
    - run: sudo apt install -y lcov
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: melos bootstrap
    - run: melos run coverage
    - uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos 2.9.0
    - run: melos bootstrap
    - run: melos run test

  integration:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub global activate melos 2.9.0
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: melos bootstrap
    - run: melos exec -c 1 --dir-exists=integration_test -- \
        xvfb-run -a xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' \
            flutter test integration_test
